name: Run tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Sync dependencies
        run: rye sync

      - name: Install test dependencies
        run: rye add coverage pytest

      - name: Run tests with coverage
        run: rye run python -m coverage run --source=image_classification --omit=*/__main__.py -m pytest -vv -s

      - name: Generate coverage report
        run: rye run python -m coverage report --fail-under=0

      - name: Generate HTML coverage report
        run: rye run python -m coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
